### ISSUE TITLE
Allow String (Facet Label) Transltion

### ISSUE THREAD

**Issue by spencerfinnell** [FacetWP/facetwp-polylang#1]
`pll_register_string`

> Allows plugins to add their own strings in the “strings translation” panel. The function must be called on admin side (the functions.php file is OK for themes). It is possible to register empty strings (for example when they come from options) but they won’t appear in the list table.

https://polylang.wordpress.com/documentation/documentation-for-developers/functions-reference/

**Comment by spencerfinnell** [comment]
Then this add-on should filter `facetwp_i18n` and use `pll__`

> translates a string previously registered with pll_register_string

**Comment by spencerfinnell** [comment]
Oh I see it's being filtered already. So they just need to be registered to the UI can be used to set the strings in Polylang.

**Comment by mgibbs189** [comment]
@spencerfinnell Sorry, was caught up with a FacetWP release.

If I understand correctly, on init we need to scan through every facet, applying `pll_register_string` to every dynamic string (labels, placeholders, etc). Then, using the `facetwp_i18n` hook, we wrap every string within pll__(), e.g.

```php
function apply_polylang_translations( $string ) {
    return pll__( $string );
}
add_filter( 'facetwp_i18n', 'apply_polylang_translations', 999 );
```

Does that sound right to you?

**Comment by spencerfinnell** [comment]
Yep!

**Comment by mgibbs189** [comment]
Added! See 822ffea
